Add a new workflow for rk35xx and update the workflow for rk35xx

diff --git a/.github/workflows/build-armbian-using-releases-files-rk35xx.yml b/.github/workflows/build-armbian-using-releases-files-rk35xx.yml
--- a/.github/workflows/build-armbian-using-releases-files-rk35xx.yml
+++ b/.github/workflows/build-armbian-using-releases-files-rk35xx.yml
@@ -1,9 +1,9 @@
 #==========================================================================
-# Description: Build Armbian arm64 server image
+# Description: Build Armbian using releases files
 # Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
 #==========================================================================
 
-name: Build Armbian arm64 server image for rk35xx
+name: Build Armbian using releases files for rk35xx
 
 on:
   repository_dispatch:
@@ -45,17 +45,10 @@ on:
           - wxy-oect
           - zcube1-max
       armbian_kernel:
-        description: "Select kernel version."
+        description: "Select kernel version (exp 6.1.118)."
         required: false
         default: "6.1.y"
-        type: choice
-        options:
-          - 6.1.y
-          - 6.1.115
-          - 6.1.118
-          - 6.1.141
-          - 6.1.115_6.1.118
-          - 6.1.118_6.1.141
+        type: string
       auto_kernel:
         description: "Auto use the latest kernel."
         required: false
@@ -102,7 +95,6 @@ on:
 
 env:
   TZ: Etc/UTC
-  ROOTFS_SCRIPT: compile-kernel/tools/script/docker/build_armbian_rootfs_file.sh
 
 jobs:
   build:
@@ -158,62 +150,47 @@ jobs:
           df -Th
           echo "status=success" >> ${GITHUB_OUTPUT}
 
-      - name: Download source code
+      - name: Download Armbian from Releases
         id: down
         working-directory: /builder
         if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
         run: |
-          df -hT ${PWD}
-          git clone -q --single-branch --depth=1 --branch=main https://github.com/armbian/build.git build
+          armbian_buildpath="build/output/images"
+          [[ -d "${armbian_buildpath}" ]] || mkdir -p "${armbian_buildpath}"
           ln -sf /builder/build ${{ github.workspace }}/build
           ln -sf /builder/build /home/runner/work/_actions/chenxv399/amlogic-s9xxx-armbian/main/build
-          echo "status=success" >> ${GITHUB_OUTPUT}
 
-      - name: Compile Armbian [ ${{ inputs.set_release }} ]
-        id: compile
-        working-directory: /builder
-        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
-        run: |
-          # Compile method and parameter description: https://docs.armbian.com/Developer-Guide_Build-Options
-          cd build/
-              ./compile.sh RELEASE=${{ inputs.set_release }} BOARD=odroidn2 BRANCH=current BUILD_MINIMAL=no \
-                           BUILD_ONLY=default HOST=armbian BUILD_DESKTOP=no EXPERT=yes KERNEL_CONFIGURE=no \
-                           COMPRESS_OUTPUTIMAGE="sha" SHARE_LOG=yes
-          echo "status=success" >> ${GITHUB_OUTPUT}
+          latest_version=$(curl -s \
+                -H "Accept: application/vnd.github+json" \
+                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+                https://api.github.com/repos/${{ github.repository }}/releases?per_page=20 | \
+                jq -r --arg RTK "Armbian_${{ inputs.set_release }}_arm64_" \
+                --arg BOARD "-trunk_" \
+                '[.[] | select(.tag_name | contains($RTK))] |
+                map(.assets[] | select(.browser_download_url | contains($BOARD) and endswith(".img.gz"))) |
+                sort_by(.updated_at) |
+                reverse |
+                .[0] |
+                {data: .updated_at, url: .browser_download_url}')
 
-      - name: Organize files and clear space
-        id: clean
-        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
-        run: |
-          # Organize and keep essential files, delete unnecessary files
-          chmod +x ${ROOTFS_SCRIPT}
-          ${ROOTFS_SCRIPT} -v ${{ inputs.set_release }} -s true -c true -k true -p arm64
+          [[ -z "${latest_version}" || "${latest_version}" == "null" ]] && echo "Invalid Armbian image download address." && exit 1
+          latest_updated_at="$(echo ${latest_version} | jq -r '.data')"
+          latest_url="$(echo ${latest_version} | jq -r '.url')"
 
-          # Clean build directory except output folder
-          cd build/
-          rm -rf $(ls . | grep -v "^output$" | xargs) 2>/dev/null
+          armbian_filename="${latest_url##*/}"
+          curl -fsSL "${latest_url}" -o "${armbian_buildpath}/${armbian_filename}"
+          [[ "${?}" -ne "0" ]] && echo "Invalid Armbian image download address." && exit 1
+          cd "${armbian_buildpath}" && gzip -df *.img.gz && sync
 
-          # Output cleaning result information
-          df -hT ${PWD}
           echo "build_tag=Armbian_${{ inputs.set_release }}_arm64_${{ inputs.armbian_edition }}_$(date +"%Y.%m")" >> ${GITHUB_ENV}
           echo "status=success" >> ${GITHUB_OUTPUT}
 
-      - name: Upload Armbian image to Release
-        uses: ncipollo/release-action@main
-        if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
-        with:
-          tag: ${{ env.build_tag }}
-          artifacts: build/output/images/*
-          allowUpdates: true
-          makeLatest: true
-          token: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Rebuild Armbian
+      - name: Rebuild Armbian [ ${{ inputs.set_release }} ]
         uses: chenxv399/amlogic-s9xxx-armbian@main
-        if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
+        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
         with:
           build_target: armbian
-          armbian_path: build/output/images/*.img.gz
+          armbian_path: build/output/images/*.img
           armbian_board: ${{ inputs.armbian_board }}
           armbian_kernel: ${{ inputs.armbian_kernel }}
           auto_kernel: ${{ inputs.auto_kernel }}
@@ -222,7 +199,7 @@ jobs:
           armbian_fstype: ${{ inputs.armbian_fstype }}
           builder_name: ${{ inputs.builder_name }}
 
-      - name: Upload Rebuild image to Release
+      - name: Upload Armbian image to Release
         uses: ncipollo/release-action@main
         if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
         with:
